name: Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
